apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
  namespace: bravo-mvp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
        - name: rails
          image: bravo-mvp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://bravo:bravo123@postgres.bravo-mvp:5432/bravo_db
            - name: REDIS_URL
              value: redis://redis.bravo-mvp:6379/0
            - name: RAILS_SERVE_STATIC_FILES
              value: "true"
            - name: RAILS_ENV
              value: "production"
            - name: SECRET_KEY_BASE
              value: "a_long_consistent_random_string_for_testing_123"
